name : "Update Proxies for V2RayN"

on:
  schedule:
    -cron: "0 20 * * *"

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:

    - name: Setup Python env
    - uses: actions/setup-python@v1
      with:
        python-versions: 3.7
      run: |
        python -m pip install --upgrade pip
        pip install json base64 urllib

    - name: Fetch free subscriptions
    - uses: actions/checkout@v2
      run: |
        nodeNumber=$((python ./parser.py) 2>&1)

    - name: Push to github and triger netlify to publish
      run: |
          git config --global user.name 'Timothy'
          git config --global user.email 'Timothy@users.noreply.github.com'
          git commit --allow-empty -am "Automated update with $nodeNumber nodes"
          git push
