name : "Update Proxies for V2RayN"

on:
  push:
  schedule:
  - cron: "0 20 * * *"

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python env
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - uses: actions/checkout@v2
      - name: Fetch free subscriptions
        run: |
          return=$((python ./parser.py) 2>&1)
          echo "::set-env nodeNumber=$return"

      - name: Push to github and triger netlify to publish
        run: |
          cat log > $nodeNumber
          git config --global user.name 'Timo'
          git config --global user.email 'Timo@netlify.com'
          git commit --allow-empty -am "Automated update ${{ steps.vars.nodeNumber }} nodes"
          git push
